### ISSUE TITLE
Android N and AppCompat 24.1.1

### ISSUE THREAD

**Issue by behelit** [greysonp/permiso#21]
Since upgrading my project to use:
- compileSdkVersion 24
- buildToolsVersion "24.0.0"
- and 24.1.1 support libraries
- targetSdkVersion 24

Using multiple permission requests no longer prompt sequentially.
Before the upgrade it would display 1 of 3 etc.. but now it only shows the first request. Once allowed, no more prompts are shown until the permissions are checked again, then the next un-allowed permission is displayed.

I just wanted to check if anyone else is getting this behaviour since I don't believe I've changed anything else.

I'll try to re-create it with a simple project.

**Comment by behelit** [comment]
Seems ok using the sample code upgraded to 24, I will have to dig more
but it crashes when re-requesting permissions

`07-29 09:54:20.608 4352-4352/com.greysonparrelli.permisodemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.greysonparrelli.permisodemo, PID: 4352
                                                                               android.content.res.Resources$NotFoundException: String resource ID #0x7f06002c
                                                                                   at android.content.res.Resources.getText(Resources.java:331)
                                                                                   at android.widget.Toast.makeText(Toast.java:287)
                                                                                   at com.greysonparrelli.permisodemo.MainActivity$6.onPermissionResult(MainActivity.java:99)
                                                                                   at com.greysonparrelli.permiso.Permiso.requestPermissions(Permiso.java:112)
                                                                                   at com.greysonparrelli.permisodemo.MainActivity.onMultipleClick(MainActivity.java:89)
                                                                                   at com.greysonparrelli.permisodemo.MainActivity.access$100(MainActivity.java:17)
                                                                                   at com.greysonparrelli.permisodemo.MainActivity$2.onClick(MainActivity.java:38)
                                                                                   at android.view.View.performClick(View.java:5609)
                                                                                   at android.view.View$PerformClick.run(View.java:22259)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by behelit** [comment]
The multiple permission request behaviour changed but I was able to correct it by changing my code

For the error, it looks like you are using this in the toast message:
`numGranted + R.string.two_permission_granted`

I think you need to use:
`Toast.makeText(MainActivity.this, String.valueOf(numGranted) + getText(R.string.two_permission_granted), Toast.LENGTH_SHORT).show();`

**Comment by greysonp** [comment]
Ah, shoot. Looks like that bug snuck through in a recent PR. I'll fix it.

**Comment by greysonp** [comment]
This was fixed in pull #15 . There's another batch of PR's I expect to go in soon. Afterwards, I'll cut a version and upload it :)
